name: Generate Python Script on CRON Schedule

on:
# push code to main branch 
  schedule:
    # runs every Sunday 
    - cron: '00 00 * * 0'
  # manually trigger workflow to check 
  workflow_dispatch:

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8' 
          
      - name: Install dependencies 
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: execute py script 
        run: python generate_data.py
        
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Generated CSV files' # commit message
          add: 'data/*' # path to CSV files
          branch: main
          force: true 

